const express = require('express')
const session = require('express-session')
const SQLiteStore = require('connect-sqlite3')(session)
const helmet = require('helmet')
const cors = require('cors')
const morgan = require('morgan')
const path = require('path')
require('dotenv').config()
const app = express()
const PORT = process.env.PORT || 4000
app.use(helmet())
app.use(morgan('dev'))
app.use(express.json())
const FRONTEND_ORIGIN = process.env.FRONTEND_ORIGIN || 'http://localhost:3000'
app.use(cors({ origin: FRONTEND_ORIGIN, credentials: true }))
app.use(session({ name: process.env.SESSION_COOKIE_NAME||'sid', secret: process.env.SESSION_SECRET||'dev-secret', resave:false, saveUninitialized:false, store: new SQLiteStore({ db: process.env.SESSION_DB||'sessions.sqlite', dir: path.join(__dirname, '..', 'data') }), cookie:{ httpOnly:true, secure: process.env.NODE_ENV==='production', sameSite:'lax', maxAge:1000*60*60*24*7 } }))
const authRoutes = require('./routes/auth')
const productRoutes = require('./routes/products')
const orderRoutes = require('./routes/orders')
const adminRoutes = require('./routes/admin')
app.use('/api/auth', authRoutes)
app.use('/api/products', productRoutes)
app.use('/api/orders', orderRoutes)
app.use('/api/admin', adminRoutes)
app.post('/api/analytics/event', (req,res)=>{ const db = require('./db'); const { v4: uuidv4 } = require('uuid'); const { event_type, payload } = req.body; const id = uuidv4(); db.prepare('INSERT INTO analytics_events (id,event_type,payload) VALUES (?,?,?)').run(id, event_type||'unknown', JSON.stringify(payload||{})); res.json({ ok:true, id }) })
app.get('/health',(req,res)=>res.json({ ok:true }))
app.listen(PORT, ()=>{ console.log(`Mock backend running on http://localhost:${PORT}`); console.log('Run `npm run init-db` to initialize the database if needed.') })